# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Raid < Formula
  desc "Distributed development environment orchestration tool"
  homepage "https://github.com/8bitalex/raid"
  version "0.5.0-beta"
  license "GPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/8bitAlex/raid/releases/download/v0.5.0-beta/raid_0.5.0-beta_darwin_amd64.tar.gz"
      sha256 "a9d7d27c939a594cdff973f686801d712ee689022767b0c987fdcb9bd23d37d8"

      define_method(:install) do
        bin.install "raid"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/8bitAlex/raid/releases/download/v0.5.0-beta/raid_0.5.0-beta_darwin_arm64.tar.gz"
      sha256 "01aa8d5bbe838a40a697de765d1106f52411b0952bca4f220ef522c7125dc349"

      define_method(:install) do
        bin.install "raid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/8bitAlex/raid/releases/download/v0.5.0-beta/raid_0.5.0-beta_linux_amd64.tar.gz"
      sha256 "5edcf318b86b1881d21242fc4626de0e4e4bbb7003a160f1ef4c9c65ae43d450"
      define_method(:install) do
        bin.install "raid"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/8bitAlex/raid/releases/download/v0.5.0-beta/raid_0.5.0-beta_linux_arm64.tar.gz"
      sha256 "02078718aaa7a8253df5cd8f40d95eef58dff07f259bc3573353e41c7246d19a"
      define_method(:install) do
        bin.install "raid"
      end
    end
  end

  test do
    system "#{bin}/raid", "--version"
  end
end
